version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      - AIRFLOW__WEBSERVER__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      - AIRFLOW__CORE__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
    volumes:
      - //etc/timezone:/etc/timezone:ro
      - //etc/localtime:/etc/localtime:ro
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs


  airflow-webserver:
    image: apache/airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      - AIRFLOW__WEBSERVER__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      - AIRFLOW__CORE__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com && airflow webserver"
    depends_on:
      - postgres
    volumes:
      - .//dags:/usr/local/airflow/dags
      - .//dags:/opt/airflow/dags
      - //etc/timezone:/etc/timezone:ro
      - //etc/localtime:/etc/localtime:ro

  airflow-scheduler:
    image: apache/airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      - AIRFLOW__WEBSERVER__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      - AIRFLOW__CORE__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=

    command: airflow scheduler
    depends_on:
      - airflow-webserver
    volumes:
      - .//dags:/usr/local/airflow/dags
      - .//dags:/opt/airflow/dags
      - //etc/timezone:/etc/timezone:ro
      - //etc/localtime:/etc/localtime:ro

  airflow-worker:
      image: apache/airflow:2.7.0
      depends_on:
        - airflow-scheduler
        - airflow-webserver
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
        - AIRFLOW__WEBSERVER__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
        - AIRFLOW__CORE__SECRET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt
        - //etc/timezone:/etc/timezone:ro
        - //etc/localtime:/etc/localtime:ro
        - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
