# version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      # - mynetwork
      - psql_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      # - mynetwork
      - psql_network

    restart: unless-stopped

networks:
  # mynetwork:
  #   driver: bridge
  psql_network:
    driver: bridge
