# version: '3.8'
services:
  postgres:
    image: my_custom_postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/  # This mounts your initialization scripts
      - ./pg-config:/etc/postgresql/  # This mounts your custom pg_config (for setting PostgreSQL options)
    networks:
      # - mynetwork
      - psql_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json
      # - ./path/to/servers.json:/pgadmin4/servers.json  # Update this path

    networks:
      - psql_network

    restart: unless-stopped

networks:
  # mynetwork:
  #   driver: bridge
  psql_network:
    external: true
