version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      # - ./init-scripts:/docker-entrypoint-initdb.d # Mount folder for init scripts
    networks:
      - psql_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_PORT=8085
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFG_MONGODB_URL= mongodb://admin:password@mongo:27017/
    depends_on:
      - mongo
    ports:
      - 8085:8085
    networks:
      - psql_network
    restart: always

volumes:
  mongo_data:
    driver: local
networks:
  psql_network:
    external: true
