# version: '3.8'

services:
  mongodb:
    image: mongo:latest  # MongoDB Docker image
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Set MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: adminpassword  # Set MongoDB root password
    ports:
      - "27017:27017"  # Expose MongoDB port on localhost
    volumes:
      - ./data/db:/data/db  # Persistent storage for MongoDB data
    networks:
      - mongo_network
    restart: unless-stopped

networks:
  mongo_network:
    driver: bridge
