version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    # restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin1
      ME_CONFIG_BASICAUTH_PASSWORD: pass1
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTHDATABASE: admin
      # ME_CONFIG_SITE_BASEURL: /mongo-express
      ME_CONFIG_SITE_PORT: 8085

    ports:
      - "8085:8081"
    depends_on:

      - mongo
    networks:
      - mongo_network
    restart: unless-stopped


networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
